version: '3.7'

services:
  api:
    image: nwarabak/appointment-scheduler:1.0
    ports:
      - 8080:8080
    environment:
      - "SPRING_PROFILES_ACTIVE=postgres,random-scheduler"
    networks:
      - default
    depends_on:
      - db
  db:
    image: postgres:10
    environment:
      - POSTGRES_USER=opensesame
      - POSTGRES_PASSWORD=opensesame
      - POSTGRES_DB=appointmentdb
    ports:
      - 5432:5432
    # https://www.postgresql.org/docs/10/app-pg-isready.html
    # https://github.com/peter-evans/docker-compose-healthcheck
    # https://github.com/peter-evans/docker-compose-healthcheck/blob/master/docker-compose.yml
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U opensesame -d appointmentdb -p 5432"]
      interval: 5s
      timeout: 5s
      retries: 3